export const runInspectorFixture = {
  object: "run.inspector",
  run: {
    id: "run-1",
    actor_id: "user-1",
    auth_scope: "user:user-1",
    source: "web",
    source_event_id: "web:event-1",
    agent_id: "agent-polly",
    bundle_version: 7,
    bundle_digest: "sha256:abcdef0123456789",
    bundle_location: "/agents/polly",
    workspace_id: "workspace-1",
    root_session_id: "session-root",
    status: "failed",
    created_at: 1_786_000_000,
    updated_at: 1_786_000_120,
  },
  root_session_id: "session-root",
  child_session_ids: ["session-child-1", "session-child-2"],
  conversation_item_ids: ["item-1"],
  tasks: [
    {
      id: "task-1",
      run_id: "run-1",
      title: "Implement checkout fix",
      status: "completed",
      root_session_id: "session-root",
      child_session_id: "session-child-1",
      dispatch_title: "Checkout worker",
      purpose: "Implement the fix",
      source_event_id: "event-task-1",
      created_at: 1_786_000_010,
      updated_at: 1_786_000_080,
    },
    {
      id: "task-2",
      run_id: "run-1",
      title: "Verify checkout fix",
      status: "failed",
      root_session_id: "session-root",
      child_session_id: "session-child-2",
      dispatch_title: "Test worker",
      purpose: "Run focused tests",
      source_event_id: "event-task-2",
      created_at: 1_786_000_020,
      updated_at: 1_786_000_110,
    },
  ],
  attempts: [
    {
      id: "attempt-1",
      task_id: "task-1",
      status: "succeeded",
      child_session_id: "session-child-1",
      worker_name: "implementer",
      worker_config_path: "agents/implementer/config.yaml",
      purpose: "Implement the fix",
      harness: "codex-native",
      model: "gpt-5",
      dispatch_call_id: "call-1",
      response_id: "response-1",
      turn_id: "turn-1",
      started_at: 1_786_000_020,
      completed_at: 1_786_000_080,
      failure_code: null,
      failure_message: null,
      source_event_id: "event-attempt-1",
      created_at: 1_786_000_020,
      updated_at: 1_786_000_080,
    },
    {
      id: "attempt-2",
      task_id: "task-2",
      status: "failed",
      child_session_id: "session-child-2",
      worker_name: "tester",
      worker_config_path: "agents/tester/config.yaml",
      purpose: "Run focused tests",
      harness: "claude-sdk",
      model: "claude-sonnet",
      dispatch_call_id: "call-2",
      response_id: "response-2",
      turn_id: "turn-2",
      started_at: 1_786_000_040,
      completed_at: 1_786_000_110,
      failure_code: "TEST_COMMAND_EXIT_1",
      failure_message: "The focused test command exited with status 1",
      source_event_id: "event-attempt-2",
      created_at: 1_786_000_040,
      updated_at: 1_786_000_110,
    },
  ],
  failures: [
    {
      attempt_id: "attempt-2",
      code: "TEST_COMMAND_EXIT_1",
      message: "The focused test command exited with status 1",
    },
  ],
  agent_snapshot: {
    id: "agent-polly",
    bundle_version: 7,
    bundle_digest: "sha256:abcdef0123456789",
    bundle_location: "/agents/polly",
  },
  workspace: {
    id: "workspace-1",
    root_path: "/work/checkout",
    repositories: [
      { id: "repo-api", name: "api", path: "/work/checkout/api" },
      { id: "repo-web", name: "web", path: "/work/checkout/web" },
    ],
    created_at: 1_785_999_000,
  },
  sessions: [
    { id: "session-root", kind: "root" },
    { id: "session-child-1", kind: "child" },
    { id: "session-child-2", kind: "child" },
  ],
  dependencies: [{ task_id: "task-2", depends_on_task_id: "task-1" }],
  events: [
    {
      source: "session",
      source_event_id: "event-parent-1",
      event_type: "parent_inbox.worker_completed",
      run_id: "run-1",
      payload: {
        worker_name: "implementer",
        status: "completed",
        occurred_at: 1_786_000_081,
        stdout: "RAW_STDOUT_SECRET",
        diagnostics: {
          stderr: "RAW_STDERR_SECRET",
          arbitrary_sensitive_value: "OPAQUE_SENSITIVE_SECRET",
        },
      },
      task_id: "task-1",
      attempt_id: "attempt-1",
      session_id: "session-child-1",
      conversation_item_id: "item-1",
    },
  ],
  leases: [
    {
      id: "lease-1",
      run_id: "run-1",
      attempt_id: "attempt-1",
      child_session_id: "session-child-1",
      host_id: "host-1",
      repository_id: "repo-api",
      worktree_path: "/tmp/worktrees/checkout",
      branch: "run/checkout",
      owner_id: "worker-1",
      status: "released",
      heartbeat_at: 1_786_000_075,
      base_commit: "base123",
      output_commit: "commit456",
      created_at: 1_786_000_015,
      released_at: 1_786_000_085,
    },
  ],
  log_references: [
    { session_id: "session-root", href: "/v1/sessions/session-root/logs" },
    { session_id: "session-child-2", href: "/v1/sessions/session-child-2/logs" },
  ],
  artifact_references: [
    {
      id: "artifact-1",
      task_id: "task-1",
      attempt_id: "attempt-1",
      name: "test-report.xml",
      location: "/v1/artifacts/artifact-1",
      content_type: "application/xml",
      created_at: 1_786_000_090,
    },
    {
      id: "artifact-unsafe",
      task_id: "task-1",
      attempt_id: "attempt-1",
      name: "unsafe-report.html",
      location: "javascript:alert('artifact')",
      content_type: "text/html",
      created_at: 1_786_000_091,
    },
  ],
} as const;

export const runEvaluationFixture = {
  object: "run.evaluation",
  id: "evaluation-1",
  run_id: "run-1",
  evaluator: "deterministic-v1",
  version: 1,
  status: "final",
  metrics: {
    task_completion_rate: 0.5,
    attempt_success_rate: 0.5,
    retry_count: 1,
    blocked_count: 1,
    blocked_duration_seconds: 12,
    parallel_overlap_seconds: 40,
    max_concurrency: 2,
    worker_duration_seconds: 130,
    parent_inbox_latency_seconds: 1.5,
    parent_inbox_latency_samples: 1,
    failure_categories: { test: 1 },
    evidence_counts: {
      worktree: 1,
      commit: 1,
      artifact: 1,
      test: 1,
      session: 3,
      conversation_item: 1,
    },
  },
  workers: [
    {
      worker_name: "tester",
      session_ids: ["session-child-2"],
      task_count: 1,
      attempt_count: 1,
      success_count: 0,
      retry_count: 1,
      blocked_count: 1,
      blocked_duration_seconds: 12,
      duration_seconds: 70,
      failure_categories: { test: 1 },
    },
  ],
  evidence_refs: ["lease:lease-1", "artifact:artifact-1"],
  rubric: null,
  created_at: 1_786_000_120,
  updated_at: 1_786_000_120,
} as const;
